// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Projekat_PR111_2019.Data;

#nullable disable

namespace Web_Projekat_PR111_2019.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Artikal", b =>
                {
                    b.Property<int>("ArtikalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikalId"));

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<int>("IdKorisnika")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaArtikla")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ArtikalId");

                    b.HasIndex("IdKorisnika");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.ArtikalIPorudzbina", b =>
                {
                    b.Property<int>("IDPorudzbine")
                        .HasColumnType("int");

                    b.Property<int>("IDArtikla")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaArtikla")
                        .HasColumnType("int");

                    b.HasKey("IDPorudzbine", "IDArtikla");

                    b.HasIndex("IDArtikla");

                    b.ToTable("ArtikliIPorudzbine");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKorisnika"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PotvrdaLozinke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PotvrdaRegistracije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("StatusVerifrikacije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verifikovan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdKorisnika");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Porudzbina", b =>
                {
                    b.Property<int>("IdPorudzbine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPorudzbine"));

                    b.Property<string>("AdresaIsporuke")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("CijenaPorudzbine")
                        .HasColumnType("float");

                    b.Property<int>("IdKorisnika")
                        .HasColumnType("int");

                    b.Property<string>("KomentarPorudzbine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("StatusPorudzbine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VrijemeIsporuke")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VrijemePorudzbine")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPorudzbine");

                    b.HasIndex("IdKorisnika");

                    b.ToTable("Porudzbine");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Artikal", b =>
                {
                    b.HasOne("Web_Projekat_PR111_2019.Models.Korisnik", "Korisnik")
                        .WithMany("Artikli")
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.ArtikalIPorudzbina", b =>
                {
                    b.HasOne("Web_Projekat_PR111_2019.Models.Artikal", "Artikal")
                        .WithMany("ArtikliIPorudzbine")
                        .HasForeignKey("IDArtikla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web_Projekat_PR111_2019.Models.Porudzbina", "Porudzbina")
                        .WithMany("ArtikliIPorudzbine")
                        .HasForeignKey("IDPorudzbine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Porudzbina", b =>
                {
                    b.HasOne("Web_Projekat_PR111_2019.Models.Korisnik", "Korisnik")
                        .WithMany("Porudzbine")
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Artikal", b =>
                {
                    b.Navigation("ArtikliIPorudzbine");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Korisnik", b =>
                {
                    b.Navigation("Artikli");

                    b.Navigation("Porudzbine");
                });

            modelBuilder.Entity("Web_Projekat_PR111_2019.Models.Porudzbina", b =>
                {
                    b.Navigation("ArtikliIPorudzbine");
                });
#pragma warning restore 612, 618
        }
    }
}
